# Generated by Django 6.1.1 on 2026-09-29 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_maintenance'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='machinery.machine')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='projects.project')),
            ],
        ),
    ]
