# Generated by Django 6.1.1 on 2026-09-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_maintenance'),
        ('projects', '0002_projectmachine'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectmachine',
            constraint=models.UniqueConstraint(fields=('project', 'machine'), name='unique_project_machine'),
        ),
    ]
