# Generated by Django 6.1.1 on 2026-09-29 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmachine_unique_project_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmachine',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_machines', to='projects.project'),
        ),
    ]
