# Generated by Django 6.1.1 on 2026-09-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('FOREMAN', 'Foreman'), ('WORKER', 'Worker')], default='WORKER', max_length=20),
        ),
    ]
