# Generated by Django 6.1.1 on 2026-09-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('FOREMAN', 'Foreman'), ('WORKER', 'Worker'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('MASON', 'Mason'), ('CARPENTER', 'Carpenter'), ('PAINTER', 'Painter'), ('WELDER', 'Welder')], default='WORKER', max_length=20),
        ),
    ]
