# Generated by Django 6.1.1 on 2026-10-01 15:15

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_cover_image_project_featured_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cover_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[projects.models.validate_rating]),
        ),
    ]
