# Generated by Django 6.1.1 on 2026-09-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('EQUIPMENT_MANAGER', 'Equipment Manager'), ('ARCHITECTURAL_MANAGER', 'Architectural Manager'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=30),
        ),
    ]
