# Generated by Django 6.1.1 on 2026-09-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_drawingcategory_alter_drawing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='drawings.drawingcategory'),
        ),
    ]
