# Generated by Django 6.1.1 on 2026-10-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0003_alter_drawing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
